import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PT_Sans } from "next/font/google";
import "./globals.css";
import ThemeProviders from "./providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ptSans = PT_Sans({
  subsets: ['latin', 'cyrillic'],
  weight: ['400', '700'],
  variable: '--font-pt-sans',
});

export const metadata: Metadata = {
  title: "stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body
        className={ptSans.className}
      >
    <ThemeProviders>
      <div id="modal-root"></div>
        {children}
    </ThemeProviders>

      </body>
    </html>
  );
}
